print ("Digite seu nome")
nome = input()
print (nome)
altura = input("Digite sua altura")
print (altura)
idade = input("Digite sua idade")
print(type(idade))
salario = int(input("Salario?"))
imposto = float(input("Digite o imposto="))
